source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OdyiOS_Example', :exclusive => true do
  pod "OdyiOS", :path => "../"
end

target 'OdyiOS_Tests', :exclusive => true do
  pod "OdyiOS", :path => "../"

  pod 'FBSnapshotTestCase'
end
